### ISSUE TITLE
Could you introduce Android config in detail

### ISSUE THREAD

**Issue by cbcye** [esseak/rn-umeng#13]
After to read README file, still not understand how to import  Gradle to project, choose which folder on the Choose Path window.

![image](https://cloud.githubusercontent.com/assets/869074/17816080/e95edd36-6669-11e6-8f94-2648935c9bfd.png)

**Comment by cbcye** [comment]
I Know how to import the Gradle, but use which name and how to add the custom code ?

**Comment by esseak** [comment]
hi @cbcye 
You will find source path "$PROJECT_DIR/node_modules/rn-umeng/android" after run install script "npm install --save rn-umeng", $PROJECT_DIR is your project folder.

**Comment by cbcye** [comment]
Thank you, but is it correct? Image_1 , how to add code as Image_2
**Image_1**
![image](https://cloud.githubusercontent.com/assets/869074/17827353/f91ea3ca-66ad-11e6-9e3c-2575d9de5858.png)
**Image_2**
![image](https://cloud.githubusercontent.com/assets/869074/17827357/0fd11ad0-66ae-11e6-8b37-e7089606ceee.png)

**Comment by esseak** [comment]
In your RN's activity, you must add custom package and override 2 methods for umeng sdk. See #11

**Comment by cbcye** [comment]
Thanks for you reply, I had try to add your code into the project ,but still not work, I think it must be some configure mistake of me, below is my configure. sorry i am not familiar with Android. I use RN 0.31,

![snip20160820_3](https://cloud.githubusercontent.com/assets/869074/17829812/c9a26ebc-66ec-11e6-928f-e3d07bec4024.png)

**Comment by esseak** [comment]
Hi @cbcye 
Something wrong I found in your pic.
1. You import wrong class package ,  right is "import in.esseak.react_native_umeng.UmengPackage". Then maybe get an error because different IDE or Environment, don't let it get you down! U can fix it by AS tips.
2. "onResume" and "onPause" are two activity's Methods, you must add to your MainActivty class. Seems your project make by command "react-native init", so the MainActivty is your first activty after your application init. MainActivty extends ReactActivity provides RN root view you can see.
